import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { listAvulsas } from "@/features/avulsas/api";
import { listContatos } from "@/features/contatos/api";
import { ErrorState, LoadingState } from "@/features/shared/AsyncState";
import { listTurmas } from "@/features/turmas/api";
import { listWorkshops } from "@/features/workshops/api";

interface CalendarEvent { label: string; kind: "aula" | "workshop" | "avulsa" }
export default function CalendarioPage() {
  const [cursor, setCursor] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const turmas = useQuery({ queryKey: ["turmas"], queryFn: listTurmas }); const avulsas = useQuery({ queryKey: ["avulsas"], queryFn: listAvulsas }); const contatos = useQuery({ queryKey: ["contatos"], queryFn: listContatos }); const workshops = useQuery({ queryKey: ["workshops"], queryFn: listWorkshops });
  const events = useMemo(() => { const map = new Map<string, CalendarEvent[]>(); const add = (iso: string, event: CalendarEvent) => map.set(iso, [...(map.get(iso) ?? []), event]); const year = cursor.getFullYear(); const month = cursor.getMonth(); const days = new Date(year, month + 1, 0).getDate(); for (let day = 1; day <= days; day++) { const date = new Date(year, month, day); const iso = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; turmas.data?.filter((item) => item.dia === date.getDay()).forEach((item) => add(iso, { label: item.nome, kind: "aula" })); } avulsas.data?.forEach((item) => { if (item.data) add(item.data, { label: `Avulsa · ${contatos.data?.find((person) => person.id === item.contato_id)?.nome ?? "Aluno"}`, kind: "avulsa" }); }); workshops.data?.forEach((item) => { for (const match of item.datas?.matchAll(/(\d{2})\/(\d{2})/g) ?? []) { const iso = `${year}-${match[2]}-${match[1]}`; add(iso, { label: item.nome, kind: "workshop" }); } }); return map; }, [avulsas.data, contatos.data, cursor, turmas.data, workshops.data]);
  if (turmas.isLoading || avulsas.isLoading || contatos.isLoading || workshops.isLoading) return <LoadingState />; const error = turmas.error ?? avulsas.error ?? contatos.error ?? workshops.error; if (error) return <ErrorState error={error} />;
  const year = cursor.getFullYear(); const month = cursor.getMonth(); const first = new Date(year, month, 1).getDay(); const days = new Date(year, month + 1, 0).getDate(); const title = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(cursor); const cells = Array.from({ length: first + days }, (_, index) => index < first ? null : index - first + 1);
  return <div className="flex flex-col gap-4"><p className="max-w-2xl text-sm text-muted-foreground">Turmas semanais, workshops e avulsas: tudo num mês só.</p><div className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-4"><Button size="icon" variant="outline" aria-label="Mês anterior" onClick={() => setCursor(new Date(year, month - 1, 1))}><ChevronLeft /></Button><strong className="capitalize">{title}</strong><Button size="icon" variant="outline" aria-label="Próximo mês" onClick={() => setCursor(new Date(year, month + 1, 1))}><ChevronRight /></Button></div><div className="grid grid-cols-7">{["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"].map((day) => <div key={day} className="border-b p-2 text-center text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">{day}</div>)}{cells.map((day, index) => { if (!day) return <div key={`empty-${index}`} className="min-h-24 border-b border-r bg-muted/30" />; const iso = `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; return <div key={iso} className="min-h-24 border-b border-r p-1.5"><div className="mb-1 text-xs font-semibold text-muted-foreground">{day}</div><div className="flex flex-col gap-1">{events.get(iso)?.map((event, eventIndex) => <Badge key={`${event.label}-${eventIndex}`} variant={event.kind === "workshop" ? "info" : event.kind === "avulsa" ? "success" : "secondary"} className="block truncate rounded-md font-medium">{event.label}</Badge>)}</div></div>; })}</div></div></div>;
}
