import { useMemo, useState } from "react";
import { Copy } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { calculateClosing, formatClosingMoney } from "@/features/fechamento/domain";

export default function FechamentoPage() {
  const [values, setValues] = useState({ nome: "Isadora", mensalidade: 500, peso: 0.296, pesoEsmaltado: 0, argilaKg: 14, biscoitoKg: 30, esmalteKg: 36 });
  const result = useMemo(() => calculateClosing(values), [values]);
  const number = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: Number(value) || 0 }));
  const preset = (name: "mariana" | "isadora") => setValues((current) => name === "mariana" ? { ...current, nome: "Mariana", mensalidade: 520, peso: 0.792, pesoEsmaltado: 0 } : { ...current, nome: "Isadora", mensalidade: 500, peso: 0.296, pesoEsmaltado: 0 });
  const copy = async () => { await navigator.clipboard.writeText(result.message); toast.success("Copiado!"); };
  return <div className="flex flex-col gap-4"><p className="max-w-2xl text-sm text-muted-foreground">Digite o peso das peças e a calculadora monta o total e a mensagem de cobrança pronta pro WhatsApp.</p><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="text-xs uppercase tracking-widest text-muted-foreground">Dados do aluno</CardTitle></CardHeader><CardContent><FieldGroup><Field><FieldLabel>Nome</FieldLabel><Input value={values.nome} onChange={(event) => setValues((current) => ({ ...current, nome: event.target.value }))} /></Field><Field><FieldLabel>Mensalidade (0 = só buscar peças)</FieldLabel><Input type="number" value={values.mensalidade} onChange={(event) => number("mensalidade", event.target.value)} /></Field><div className="grid grid-cols-2 gap-3"><Field><FieldLabel>Peso das peças (kg)</FieldLabel><Input type="number" step="0.001" value={values.peso} onChange={(event) => number("peso", event.target.value)} /></Field><Field><FieldLabel>Peso esmaltado (kg)</FieldLabel><Input type="number" step="0.001" value={values.pesoEsmaltado} onChange={(event) => number("pesoEsmaltado", event.target.value)} /></Field></div><div><h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-muted-foreground">Tarifas por kg</h3><div className="grid grid-cols-2 gap-3"><Field><FieldLabel>Argila</FieldLabel><Input type="number" value={values.argilaKg} onChange={(event) => number("argilaKg", event.target.value)} /></Field><Field><FieldLabel>1ª queima</FieldLabel><Input type="number" value={values.biscoitoKg} onChange={(event) => number("biscoitoKg", event.target.value)} /></Field></div></div><Field><FieldLabel>2ª queima (esmalte)</FieldLabel><Input type="number" value={values.esmalteKg} onChange={(event) => number("esmalteKg", event.target.value)} /></Field></FieldGroup></CardContent></Card><div className="flex flex-col gap-3"><Card className="bg-secondary/40"><CardHeader><CardTitle>Fechamento</CardTitle><CardDescription>Detalhamento do mês</CardDescription></CardHeader><CardContent><div className="flex flex-col">{result.lines.map((line) => <div key={line.label} className="flex justify-between border-b border-dashed py-2 text-sm"><span className="text-muted-foreground">{line.label}</span><span>{formatClosingMoney(line.value)}</span></div>)}<div className="mt-2 flex justify-between border-t-2 border-foreground pt-3 font-bold"><span>Total</span><span>{formatClosingMoney(result.total)}</span></div></div></CardContent></Card><Textarea className="min-h-44 bg-card" readOnly value={result.message} /><div className="flex flex-wrap gap-2"><Button onClick={() => void copy()}><Copy data-icon="inline-start" />Copiar mensagem</Button><Button variant="outline" onClick={() => preset("mariana")}>Ex.: Mariana</Button><Button variant="outline" onClick={() => preset("isadora")}>Ex.: Isadora</Button></div></div></div></div>;
}
